"""
Compliance Pilot — Document filler: write answers back into questionnaire files.
"""

import os
import re
from pathlib import Path
from typing import List, Dict, Any
from datetime import datetime


def _strip_markdown(text: str) -> str:
    """Remove common Markdown formatting so answers render as clean plain text
    in Word/Excel/PDF outputs. Preserves the underlying words — only the syntax."""
    if not text:
        return text
    # Code fences and inline code — keep the inner text
    text = re.sub(r"```[a-zA-Z]*\n?", "", text)
    text = text.replace("```", "")
    text = re.sub(r"`([^`]+)`", r"\1", text)
    # Bold / italic: ***x***, **x**, __x__, *x*, _x_
    text = re.sub(r"\*\*\*(.+?)\*\*\*", r"\1", text, flags=re.DOTALL)
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text, flags=re.DOTALL)
    text = re.sub(r"__(.+?)__", r"\1", text, flags=re.DOTALL)
    text = re.sub(r"(?<![\*\w])\*(?!\s)(.+?)(?<!\s)\*(?![\*\w])", r"\1", text, flags=re.DOTALL)
    text = re.sub(r"(?<![_\w])_(?!\s)(.+?)(?<!\s)_(?![_\w])", r"\1", text, flags=re.DOTALL)
    # Markdown links [label](url) -> label (url)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1 (\2)", text)
    # Leading heading hashes: "## Heading" -> "Heading"
    text = re.sub(r"^\s{0,3}#{1,6}\s+", "", text, flags=re.MULTILINE)
    # Blockquote markers at line start
    text = re.sub(r"^\s{0,3}>\s?", "", text, flags=re.MULTILINE)
    # Clean any stray leftover ** or __ pairs
    text = text.replace("**", "").replace("__", "")
    # Strip [Source: ...] citations the LLM may echo from context
    text = re.sub(r"\s*\[Source:[^\]]*\]", "", text)
    return text.strip()


_PROJECT_ROOT = Path(__file__).parent.parent
OUTPUT_DIR = Path(os.getenv("OUTPUT_DIR", str(_PROJECT_ROOT / "outputs")))
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


async def fill_document(
    file_path: str, file_type: str, qa_pairs: List[Dict[str, Any]], version: int
) -> str:
    """
    Fill answers into the original questionnaire document.
    Returns path to the filled output file.
    """
    file_type = file_type.lower().lstrip(".")

    if file_type == "docx":
        return _fill_docx(file_path, qa_pairs, version)
    elif file_type == "xlsx":
        return _fill_xlsx(file_path, qa_pairs, version)
    elif file_type == "txt":
        return _fill_txt_as_docx(file_path, qa_pairs, version)
    elif file_type == "pdf":
        return _fill_pdf(file_path, qa_pairs, version)
    elif file_type == "json":
        return _fill_json(file_path, qa_pairs, version)
    else:
        raise ValueError(f"Unsupported file type: {file_type}")


def _format_answer(qa: dict) -> str:
    """Format answer text based on confidence tier."""
    answer = _strip_markdown(qa.get("answer_text", "") or "")
    tier = qa.get("confidence_tier", "no_answer")
    sources = qa.get("sources", [])

    if tier == "no_answer" or not answer:
        return "\U0001f6a9 No confident answer found \u2014 human review required"
    elif tier == "needs_review":
        return f"\u26a0 Needs Review: {answer}"
    else:
        return answer


def _footer_text(version: int) -> str:
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    return f"Answers generated by Compliance Pilot v1 \u2014 KB version: {version} \u2014 {timestamp}"


def _fill_docx(file_path: str, qa_pairs: List[Dict[str, Any]], version: int) -> str:
    """Fill answers into DOCX table cells and after paragraph questions."""
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.oxml.ns import qn

    doc = Document(file_path)

    # 1. Fill table-based Q&A
    for qa in qa_pairs:
        loc = qa["location_info"]
        if loc.get("type") != "docx_table":
            continue

        table_idx = loc["table_index"]
        row_idx = loc["row_index"]
        answer_col = loc.get("answer_col", loc.get("col_index", 1))

        if table_idx < len(doc.tables):
            table = doc.tables[table_idx]
            if row_idx < len(table.rows):
                cell = table.rows[row_idx].cells[answer_col]
                cell.text = _format_answer(qa)

    # 2. Fill paragraph-based Q&A — insert answer paragraph after each question
    # Build a map of paragraph_index → qa_pair
    para_answers = {}
    for qa in qa_pairs:
        loc = qa["location_info"]
        if loc.get("type") == "docx_paragraph":
            p_idx = loc.get("paragraph_index")
            if p_idx is not None:
                para_answers[p_idx] = qa

    if para_answers:
        # We need to insert new paragraphs after question paragraphs.
        # Work in reverse order so indices don't shift.
        for p_idx in sorted(para_answers.keys(), reverse=True):
            qa = para_answers[p_idx]
            answer_text = _format_answer(qa)
            tier = qa.get("confidence_tier", "no_answer")

            if p_idx < len(doc.paragraphs):
                question_para = doc.paragraphs[p_idx]

                # Create a new paragraph element after the question
                new_para = doc.add_paragraph()
                # Move it right after the question paragraph
                question_para._element.addnext(new_para._element)

                # Style the answer
                run = new_para.add_run(f"\u2794 {answer_text}")
                run.font.size = Pt(10)
                run.italic = True

                if tier == "auto_fill":
                    run.font.color.rgb = RGBColor(0x1E, 0x88, 0x3E)  # green
                elif tier == "needs_review":
                    run.font.color.rgb = RGBColor(0xE6, 0x5C, 0x00)  # orange
                else:
                    run.font.color.rgb = RGBColor(0xD3, 0x2F, 0x2F)  # red

    # Add footer
    para = doc.add_paragraph()
    run = para.add_run(_footer_text(version))
    run.font.size = Pt(8)
    run.italic = True

    output_path = OUTPUT_DIR / f"filled_{Path(file_path).stem}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.docx"
    doc.save(str(output_path))
    return str(output_path)


def _fill_json(file_path: str, qa_pairs: List[Dict[str, Any]], version: int) -> str:
    """Fill answers into a JSON file and return as a new JSON."""
    import json

    output_data = {
        "generated_by": "Compliance Pilot",
        "kb_version": version,
        "timestamp": datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        "results": [],
    }

    for qa in qa_pairs:
        output_data["results"].append({
            "question": qa.get("question_text", ""),
            "answer": _format_answer(qa),
            "confidence_score": qa.get("confidence_score", 0),
            "confidence_tier": qa.get("confidence_tier", "no_answer"),
            "sources": qa.get("sources", []),
        })

    output_path = OUTPUT_DIR / f"filled_{Path(file_path).stem}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(output_data, f, indent=2, ensure_ascii=False)
    return str(output_path)

def _fill_xlsx(file_path: str, qa_pairs: List[Dict[str, Any]], version: int) -> str:
    """Fill answers into XLSX cells across all sheets."""
    from openpyxl import load_workbook
    from openpyxl.styles import Alignment

    wb = load_workbook(file_path)
    wrap_alignment = Alignment(wrap_text=True, vertical="top")

    for qa in qa_pairs:
        loc = qa["location_info"]
        if loc.get("type") != "xlsx":
            continue

        row = loc["row"]
        col = loc.get("answer_col", "B")
        sheet_name = loc.get("sheet")

        # Find the correct sheet
        if sheet_name and sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
        else:
            ws = wb.active

        cell = ws[f"{col}{row}"]
        cell.value = _format_answer(qa)
        cell.alignment = wrap_alignment

    # Set answer column width to 80 chars — detect actual answer columns used
    answer_cols_per_sheet = {}
    for qa in qa_pairs:
        loc = qa["location_info"]
        if loc.get("type") == "xlsx":
            sheet = loc.get("sheet", wb.active.title)
            col = loc.get("answer_col", "B")
            if sheet not in answer_cols_per_sheet:
                answer_cols_per_sheet[sheet] = set()
            answer_cols_per_sheet[sheet].add(col)

    for ws in wb.worksheets:
        cols = answer_cols_per_sheet.get(ws.title, {"B"})
        for col in cols:
            ws.column_dimensions[col].width = 80

    # Add footer to each sheet that had answers
    sheets_with_answers = set()
    for qa in qa_pairs:
        loc = qa["location_info"]
        if loc.get("type") == "xlsx" and loc.get("sheet"):
            sheets_with_answers.add(loc["sheet"])

    for sheet_name in sheets_with_answers or [wb.active.title]:
        if sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
            last_row = ws.max_row + 2
            ws[f"A{last_row}"] = _footer_text(version)

    output_path = OUTPUT_DIR / f"filled_{Path(file_path).stem}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.xlsx"
    wb.save(str(output_path))
    return str(output_path)


def _fill_pdf(file_path: str, qa_pairs: List[Dict[str, Any]], version: int) -> str:
    """Fill PDF form fields, or generate DOCX if no form fields."""
    import fitz

    doc = fitz.open(file_path)
    has_form_fields = False
    filled_count = 0

    # Build lookup: field_name → qa_pair (from location_info)
    field_map = {}
    for qa in qa_pairs:
        loc = qa.get("location_info", {})
        if loc.get("type") == "pdf_form_field" and loc.get("field_name"):
            field_map[loc["field_name"]] = qa

    for page in doc:
        for widget in (page.widgets() or []):
            has_form_fields = True
            field_name = (widget.field_name or "").strip()
            if not field_name:
                continue

            # 1. Exact match by field_name from location_info
            matched_qa = field_map.get(field_name)

            # 2. Fuzzy match: compare field_name/label against question text
            if not matched_qa:
                label = (widget.field_label or "").strip()
                for qa in qa_pairs:
                    q_text = qa.get("question_text", "")
                    if _fuzzy_field_match(field_name, label, q_text):
                        matched_qa = qa
                        break

            if matched_qa:
                widget.field_value = _format_answer(matched_qa)
                widget.update()
                filled_count += 1

    if has_form_fields:
        # Add footer as text annotation on last page
        last_page = doc[-1]
        footer = _footer_text(version)
        rect = fitz.Rect(50, last_page.rect.height - 30, last_page.rect.width - 50, last_page.rect.height - 10)
        last_page.insert_textbox(rect, footer, fontsize=7, color=(0.4, 0.4, 0.4))

        output_path = OUTPUT_DIR / f"filled_{Path(file_path).stem}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"
        doc.save(str(output_path))
        doc.close()
        print(f"PDF form filled: {filled_count}/{len(qa_pairs)} fields matched")
        return str(output_path)

    doc.close()
    # No form fields — generate DOCX instead
    return _fill_txt_as_docx(file_path, qa_pairs, version)


def _fuzzy_field_match(field_name: str, field_label: str, question_text: str) -> bool:
    """Check if a PDF form field matches a question text."""
    q_lower = question_text.strip().lower()
    fn_lower = field_name.strip().lower()
    fl_lower = field_label.strip().lower()

    # Direct containment checks
    if fn_lower and (fn_lower in q_lower or q_lower in fn_lower):
        return True
    if fl_lower and len(fl_lower) >= 5 and (fl_lower in q_lower or q_lower in fl_lower):
        return True

    # Normalize: remove underscores, hyphens, extra spaces
    def normalize(s):
        return " ".join(s.replace("_", " ").replace("-", " ").lower().split())

    nq = normalize(question_text)[:60]
    nf = normalize(field_name)[:60]
    nl = normalize(field_label)[:60]

    if nf and (nf in nq or nq in nf):
        return True
    if nl and len(nl) >= 5 and (nl in nq or nq in nl):
        return True

    return False


def _fill_txt_as_docx(file_path: str, qa_pairs: List[Dict[str, Any]], version: int) -> str:
    """Generate a DOCX from TXT/PDF questions with answers."""
    from docx import Document
    from docx.shared import Pt

    doc = Document()
    doc.add_heading("Compliance Pilot \u2014 Filled Questionnaire", level=1)

    table = doc.add_table(rows=1, cols=2)
    table.style = "Table Grid"
    hdr = table.rows[0].cells
    hdr[0].text = "Question"
    hdr[1].text = "Answer"

    for cell in hdr:
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.bold = True

    for qa in qa_pairs:
        row = table.add_row().cells
        row[0].text = qa.get("question_text", "")
        row[1].text = _format_answer(qa)

    para = doc.add_paragraph()
    run = para.add_run(_footer_text(version))
    run.font.size = Pt(8)
    run.italic = True

    output_path = OUTPUT_DIR / f"filled_{Path(file_path).stem}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.docx"
    doc.save(str(output_path))
    return str(output_path)
